"""Graphical maze display using MiniLibX.

Conforms to the A-Maze-ing subject (Part V - Visual representation).
Adapted for the existing MazeGenerator class.
"""

import random
import time
from typing import Tuple, Set, Optional, Dict, Any, List
from collections import deque
from mlx import Mlx
from mazegen.generator import MazeGenerator, ALL_WALLS, EAST, SOUTH, OPPOSITE
from solver import solve, solve_animated, Coord
from a_maze_ing import save_maze


class MlxDisplay:
    """
    MLX maze display for MazeGenerator.

    Implements the interactions required by the subject:
        - Regenerate a maze (R)
        - Show/Hide the solution path (P)
        - Change wall colors (C)
    """

    COLORS: Dict[str, int] = {
        'wall': 0xFFFFFFFF,
        'floor': 0xFF000000,
        'entry': 0xFF2ECC71,     
        'exit': 0xFFE74C3C,      
        'path': 0xFF888888,      
        'pattern42': 0xFFFFFFFF,  
        'gen_current': 0xFFF1C40F,  
        'visited': 0xFF16213e,
        'frontier': 0xFF0f3460,
        'current': 0xFFe94560,
    }
    # Wall color (changeable via 'C' key)
    _wall_color: int = COLORS['wall']

    def __init__(self, maze: MazeGenerator, cell_size: int = 30,
                 entry: Tuple[int, int] = (0, 0),
                 exit_pos: Optional[Tuple[int, int]] = None,
                 output_file: str = "output.txt"):
        """
        Initialize the MLX window.

        Args:
            maze: Maze generated by MazeGenerator
            cell_size: Cell size in pixels
            entry: Entry coordinates (x, y) - default (0, 0)
            exit_pos: Exit coordinates (x, y) - default (width-1, height-1)
        """
        self.maze = maze
        self.cell_size = cell_size
        self.show_path: bool = False  # Path hidden by default
        # Wall line thickness in pixels. Change this value to make the
        # maze separators thicker or thinner.
        self.wall_thickness: int = 2

        # Store entry and exit
        self.entry = entry
        self.output_file = output_file
        if exit_pos is None:
            self.exit_pos = (maze.width - 1, maze.height - 1)
        else:
            self.exit_pos = exit_pos

        # --- Path animation attributes ---
        self._path_cells: List[Tuple[int, int]] = []
        self._path_progress: int = 0
        self._animating: bool = False
        self._frame_counter: int = 0
        self._animation_speed: int = 1
        self._path_dir_map: Dict[Tuple[int, int], str] = {}
        self._gen_steps: List[Tuple[int, int, int, int, int]] = []
        self._gen_grid: List[List[int]] = []
        self._gen_progress: int = 0
        self._gen_animating: bool = False
        self._gen_steps_per_sec: float = 5
        self._gen_target_duration: float = 15
        self._gen_start_time: float = 0.0
        self._gen_current: Optional[Tuple[int, int]] = None

        self.bfs_mode: bool = False
        self.bfs_animator: Optional['BFSAnimator'] = None
        self.bfs_frame_counter: int = 0
        self.bfs_speed: int = 1
        self.bfs_complete_counter: int = 0
        self.bfs_show_duration: int = 30

        self.bfs_final_state: Optional[dict[str, Any]] = None

        self._path_coords: Set[Tuple[int, int]] = set()
        self._path_directions: List[str] = []
        self._solve_path()

        self.width = maze.width * cell_size + 2
        self.height = maze.height * cell_size + 2

        self.mlx = Mlx()
        self.mlx_ptr = self.mlx.mlx_init()
        if not self.mlx_ptr:
            raise RuntimeError("mlx_init() failed")

        self.win = self.mlx.mlx_new_window(
            self.mlx_ptr,
            self.width,
            self.height,
            "A-Maze-Ing"
        )
        if not self.win:
            self.mlx.mlx_release(self.mlx_ptr)
            raise RuntimeError("mlx_new_window() failed")

        # --- 3. Create the image buffer ---
        self.img = self.mlx.mlx_new_image(
            self.mlx_ptr, self.width, self.height)
        self.data, self.bpp, self.sl, _ = self.mlx.mlx_get_data_addr(self.img)

        # --- 4. Register hooks ---
        self.mlx.mlx_key_hook(self.win, self._on_key, None)
        self.mlx.mlx_hook(self.win, 33, 0, self._on_close, None)
        self.mlx.mlx_loop_hook(self.mlx_ptr, self._render, None)
        self._start_generation_animation()

        print("MLX Commands:")
        print("  [R] Re-generate a new maze")
        print("  [P] Show/Hide the solution path (step by step)")
        print("  [F] Stop aniamation maze")
        print("  [B] Solve animation (BFS or A*, per ALGORITHM in config; "
              "auto-plays step by step)")
        print("  [D] Display solution instantly")
        print("  [C] Change wall colors")
        print("  [S] Save")
        print("  [G] Replay the maze generation animation" )
        print("  [Q] / [Esc] Quit")

    def _start_generation_animation(self) -> None:
        """(Re)starts the DFS carving animation from a blank grid.

        Rebuilds an all-walls grid and replays self.maze.steps on it
        frame by frame. Cells that are part of the '42' pattern stay
        ALL_WALLS throughout, since no step ever targets them.
        """
        self._gen_steps = list(self.maze.steps)
        self._gen_grid = [
            [ALL_WALLS for _ in range(self.maze.width)]
            for _ in range(self.maze.height)
        ]
        self._gen_progress = 0
        self._gen_start_time = time.monotonic()
        self._gen_current = self.entry
        self._gen_animating = bool(self._gen_steps)

        if self._gen_steps:
            ideal = len(self._gen_steps) / self._gen_target_duration
            self._gen_steps_per_sec = max(5.0, min(200.0, ideal))

    def _skip_generation_animation(self) -> None:
        """Instantly completes the DFS reveal animation, if running.

        self.maze.grid is already the fully-carved maze the moment
        MazeGenerator.generate() returns; _gen_grid/_gen_animating only
        control the *cosmetic* wall-by-wall replay used on screen. So
        jumping straight to "done" here doesn't skip any real work, it
        just stops making the user wait for the replay before showing
        something else (BFS, the solution path, ...).
        """
        if self._gen_animating or self._gen_progress < len(self._gen_steps):
            self._gen_progress = len(self._gen_steps)
            self._gen_animating = False
            self._gen_current = None

    def _solve_path(self) -> None:
        """Solve the maze and store ordered cells with directions."""
        path_dirs = solve(self.maze.grid, self.entry, self.exit_pos)

        if path_dirs is None:
            self._path_directions = []
            self._path_coords = set()
            self._path_cells = []
            self._path_dir_map = {}
            return

        self._path_directions = path_dirs

        # Convert directions to coordinates (ordered list)
        x, y = self.entry
        coords = [(x, y)]
        dir_map = {}
        for d in path_dirs:
            dir_map[(x, y)] = d  # Store direction for current cell
            if d == 'N':
                y -= 1
            elif d == 'S':
                y += 1
            elif d == 'E':
                x += 1
            elif d == 'W':
                x -= 1
            coords.append((x, y))

        self._path_cells = coords
        self._path_coords = set(coords)
        self._path_dir_map = dir_map

    def _update_path(self) -> None:
        """Update path after maze regeneration."""
        self._solve_path()

    # ==========================================================
    #  RENDERING
    # ==========================================================

    def _put_pixel(self, x: int, y: int, color: int) -> None:
        """Write a pixel to the image buffer."""
        if 0 <= x < self.width and 0 <= y < self.height:
            off = y * self.sl + x * (self.bpp // 8)
            self.data[off:off+4] = color.to_bytes(4, 'little')

    def _draw_rect(self, x: int, y: int, w: int, h: int, color: int) -> None:
        """Draw a filled rectangle."""
        for row in range(y, y + h):
            for col in range(x, x + w):
                self._put_pixel(col, row, color)

    def _draw_line(
            self, x1: int, y1: int, x2: int, y2: int, color: int) -> None:
        """Draw a line using Bresenham's algorithm."""
        dx = abs(x2 - x1)
        dy = abs(y2 - y1)
        sx = 1 if x1 < x2 else -1
        sy = 1 if y1 < y2 else -1
        err = dx - dy

        while True:
            self._put_pixel(x1, y1, color)
            if x1 == x2 and y1 == y2:
                break
            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x1 += sx
            if e2 < dx:
                err += dx
                y1 += sy

    def _draw_thick_line(
            self, x1: int, y1: int, x2: int, y2: int,
            color: int, thickness: int = 4) -> None:
        """Draw a thick line."""
        if x1 == x2:  # Vertical line
            for i in range(thickness):
                self._draw_line(x1 - i, y1, x2 - i, y2, color)
        elif y1 == y2:  # Horizontal line
            for i in range(thickness):
                self._draw_line(x1, y1 - i, x2, y2 - i, color)
        else:  # Diagonal line - offset multiple lines
            for i in range(thickness):
                self._draw_line(x1 - i, y1 - i, x2 - i, y2 - i, color)

    def _draw_arrow(self, cx: int, cy: int, direction: str, color: int,
                    size: int = 10, thickness: int = 2) -> None:
        """Draw an arrow centered at (cx, cy) pointing in direction."""
        half = size // 2

        if direction == 'N':
            x1, y1 = cx, cy + half
            x2, y2 = cx, cy - half
            x3, y3 = cx - half//2, cy - half//2
            x4, y4 = cx + half//2, cy - half//2
        elif direction == 'S':
            x1, y1 = cx, cy - half
            x2, y2 = cx, cy + half
            x3, y3 = cx - half//2, cy + half//2
            x4, y4 = cx + half//2, cy + half//2
        elif direction == 'E':
            x1, y1 = cx - half, cy
            x2, y2 = cx + half, cy
            x3, y3 = cx + half//2, cy - half//2
            x4, y4 = cx + half//2, cy + half//2
        elif direction == 'W':
            x1, y1 = cx + half, cy
            x2, y2 = cx - half, cy
            x3, y3 = cx - half//2, cy - half//2
            x4, y4 = cx - half//2, cy + half//2
        else:
            return

        # Body of the arrow
        self._draw_thick_line(x1, y1, x2, y2, color, thickness)
        # Arrowhead
        self._draw_line(x2, y2, x3, y3, color)
        self._draw_line(x2, y2, x4, y4, color)

    def _clear(self) -> None:
        """Clear the buffer to black."""
        size = self.sl * self.height
        self.data[0:size] = b'\x00\x00\x00\xff' * (size // 4)

    def _flush(self) -> None:
        """Send the buffer to the window."""
        self.mlx.mlx_put_image_to_window(
            self.mlx_ptr, self.win, self.img, 0, 0)

    def _render(self, data: Any) -> None:
        """Called every frame by mlx_loop_hook."""
        # Generation (DFS carving) animation runs first and exclusively:
        # nothing else is meaningful to animate while walls are still
        # being revealed (path/BFS both operate on the finished maze).
        if self._gen_animating:
            self._advance_generation()
        else:
            # Progressive path animation
            if self._animating:
                self._frame_counter += 1
                if self._frame_counter >= self._animation_speed:
                    self._frame_counter = 0
                    if self._path_progress < len(self._path_cells):
                        self._path_progress += 1
                    else:
                        self._animating = False  # Animation complete

            # BFS auto-play animation
            # BFS auto-play animation
        if self.bfs_mode and self.bfs_animator:

            if not self.bfs_animator.is_finished():

                self.bfs_frame_counter += 1

                if self.bfs_frame_counter >= self.bfs_speed:
                    self.bfs_frame_counter = 0
                    self.bfs_animator.next_step()

            else:
                # Keep the last animation state forever
                self.bfs_final_state = self.bfs_animator.get_state(
                    self.bfs_animator.current_step
                )

                self.bfs_mode = False
                self.bfs_animator = None        

        self._clear()

        generating = self._gen_animating or self._gen_progress < len(
            self._gen_steps)
        if not generating:

            if self.bfs_mode and self.bfs_animator:

                state = self.bfs_animator.get_state(
                    self.bfs_animator.current_step
                )

                self._draw_bfs_step(state)

            elif self.bfs_final_state:

                self._draw_bfs_step(self.bfs_final_state)

            else:

                self._draw_maze()

        else:

            self._draw_maze()

        self._flush()
        self._draw_info()

    def _advance_generation(self) -> None:
        """Reveals DFS steps of the generation animation, paced by
        real elapsed time rather than by the number of hook calls.

        Each revealed step reopens the wall pair recorded by
        MazeGenerator._remove_wall on self._gen_grid, and moves the
        "current cell" cursor to the newly carved cell, mimicking the
        recursive-backtracker's frontier as it explores/backtracks.
        """
        elapsed = time.monotonic() - self._gen_start_time
        target = min(
            len(self._gen_steps),
            int(elapsed * self._gen_steps_per_sec),
        )
        while self._gen_progress < target:
            x, y, nx, ny, direction = self._gen_steps[self._gen_progress]
            self._gen_grid[y][x] &= ~direction
            self._gen_grid[ny][nx] &= ~OPPOSITE[direction]
            self._gen_current = (nx, ny)
            self._gen_progress += 1

        if self._gen_progress >= len(self._gen_steps):
            self._gen_animating = False
            self._gen_current = None

    def _draw_maze(self) -> None:
        """Draw the maze with progressive path display."""
        generating = self._gen_animating or self._gen_progress < len(
            self._gen_steps)
        grid = self._gen_grid if generating else self.maze.grid

        # Visible path cells (progressive or full). The solution path is
        # only meaningful once the maze is fully carved, so it stays
        # hidden while the generation animation is still running.
        visible_path = set()
        if self.show_path and not generating:
            if self._animating:
                limit = self._path_progress
            else:
                limit = len(self._path_cells)
            visible_path = set(self._path_cells[:limit])

        for y in range(self.maze.height):
            for x in range(self.maze.width):
                px = x * self.cell_size + 1
                py = y * self.cell_size + 1
                walls = grid[y][x]

                # --- Determine background color ---
                if generating and (x, y) == self._gen_current:
                    color = self.COLORS['gen_current']
                elif (x, y) == self.entry:
                    color = self.COLORS['entry']
                elif (x, y) == self.exit_pos:
                    color = self.COLORS['exit']
                elif (x, y) in visible_path:
                    color = self.COLORS['path']  # Highlight path cells
                elif walls == ALL_WALLS:
                    color = self.COLORS['pattern42']
                else:
                    color = self.COLORS.get('floor', 0xFFFFFFFF)

                self._draw_rect(px, py, self.cell_size, self.cell_size, color)

                # --- Draw arrow if cell is in path (except entry/exit) ---
                pos = (x, y)
                if (
                     pos in visible_path and
                     pos not in (self.entry, self.exit_pos)):
                    direction = self._path_dir_map.get((x, y))
                    if direction:
                        cx = px + self.cell_size // 2
                        cy = py + self.cell_size // 2
                        arrow_size = self.cell_size // 3  # Smaller arrow
                        self._draw_arrow(
                            cx, cy, direction,
                            self.COLORS['path'],
                            size=arrow_size, thickness=2)

                # --- Walls ---
                wall_color = self._wall_color
                if walls & EAST:
                    self._draw_thick_line(
                        px + self.cell_size, py,
                        px + self.cell_size, py + self.cell_size,
                        wall_color, thickness=self.wall_thickness)
                if walls & SOUTH:
                    self._draw_thick_line(px, py + self.cell_size,
                                          px + self.cell_size,
                                          py + self.cell_size,
                                          wall_color,
                                          thickness=self.wall_thickness)

        # Outer borders
        wall_color = self._wall_color
        t = self.wall_thickness
        self._draw_thick_line(0, 0, self.width, 0, wall_color, thickness=t)
        self._draw_thick_line(0, self.height - 1, self.width, self.height - 1,
                              wall_color, thickness=t)
        self._draw_thick_line(0, 0, 0, self.height, wall_color, thickness=t)
        self._draw_thick_line(self.width - 1, 0, self.width - 1, self.height,
                              wall_color, thickness=t)

    def _draw_bfs_step(self, state: dict[str, Any]) -> None:
        """Draw the current BFS animation step.

        Colors:
            - Green: Entry
            - Red: Exit
            - Dark blue: Visited cells
            - Blue: Frontier (queue)
            - Red: Current cell being explored
            - Gray: Current path
            - White: Walls
            - Black: Floor

        Args:
            state: Dict with 'visited', 'frontier', 'current', 'path' keys
        """
        grid = self.maze.grid
        colors = self.COLORS

        visited = state.get('visited', set())
        frontier = state.get('frontier', deque())
        current = state.get('current', self.entry)

        # Build current path coordinates
        path_cells = set()
        if state.get('path'):
            x, y = self.entry
            path_cells.add((x, y))
            for d in state['path']:
                if d == 'N':
                    y -= 1
                elif d == 'S':
                    y += 1
                elif d == 'E':
                    x += 1
                elif d == 'W':
                    x -= 1
                path_cells.add((x, y))

        for y in range(self.maze.height):
            for x in range(self.maze.width):
                px = x * self.cell_size + 1
                py = y * self.cell_size + 1
                walls = grid[y][x]
                pos = (x, y)

                # Determine cell color
                if pos == self.entry:
                    color = colors['entry']
                elif pos == self.exit_pos:
                    color = colors['exit']
                elif pos == current:
                    color = colors['current']
                elif pos in path_cells and pos != self.entry:
                    color = colors['path']
                elif pos in visited:
                    color = colors['visited']
                elif pos in frontier:
                    color = colors['frontier']
                elif walls == ALL_WALLS:
                    color = colors['wall']
                else:
                    color = colors['floor']

                self._draw_rect(px, py, self.cell_size, self.cell_size, color)

                # Draw walls
                wall_color = colors['wall']
                if walls & EAST:
                    self._draw_thick_line(px + self.cell_size, py,
                                          px + self.cell_size,
                                          py + self.cell_size,
                                          wall_color, thickness=2)
                if walls & SOUTH:
                    self._draw_thick_line(px, py + self.cell_size,
                                          px + self.cell_size,
                                          py + self.cell_size,
                                          wall_color, thickness=2)

        # Outer borders
        wall_color = colors['wall']
        self._draw_thick_line(0, 0, self.width, 0, wall_color, thickness=2)
        self._draw_thick_line(0, self.height - 1, self.width, self.height - 1,
                              wall_color, thickness=2)
        self._draw_thick_line(0, 0, 0, self.height, wall_color, thickness=2)
        self._draw_thick_line(self.width - 1, 0, self.width - 1, self.height,
                              wall_color, thickness=2)

    def _draw_info(self) -> None:
        """Display information at the bottom of the window."""
        y = self.maze.height * self.cell_size + 5
        steps = len(self._path_directions)

        if self._gen_animating:
            pct = int(100 * self._gen_progress / max(1, len(self._gen_steps)))
            text = f"Generating maze... {pct}%"
        elif self.bfs_mode and self.bfs_animator:
            progress = int(self.bfs_animator.get_progress() * 100)
            algo_name = self.bfs_animator.algorithm.upper()
            status = algo_name if not self.bfs_animator.is_finished() else "DONE"
            text = (f"{algo_name}: {status} | Progress: {progress}% | "
                    f"Size: {self.maze.width}x{self.maze.height}")
        else:
            text = (f"Size: {self.maze.width}x{self.maze.height} | "
                    f"Path: {'ON' if self.show_path else 'OFF'} | "
                    f"Steps: {steps} | "
                    f"42: {'✅' if self.maze.pattern_placed else '⚠️'}")

        self.mlx.mlx_string_put(
            self.mlx_ptr, self.win, 10, y + 25, 0xFFFFFFFF, text)

    # ==========================================================
    #  EVENT HANDLERS
    # ==========================================================

    def _on_key(self, keycode: int, data: Any) -> None:
        """Handle keyboard events."""

        if keycode in (65307, 113):
            self._quit()

        elif keycode in (114, 82):
            self._regenerate()

        elif keycode in (102, 70):
            self._skip_generation_animation()

        elif keycode in (112, 80):
            if self.show_path:
                self.show_path = False
                self._animating = False
            else:
                self._skip_generation_animation()
                self._animating = True
                self._path_progress = 0
                self._frame_counter = 0
                self.show_path = True

        elif keycode in (100, 68):
            self._show_solution()
    
        elif keycode in (98, 66):
            self._skip_generation_animation()
            self._start_bfs_animation()

        elif keycode in (99, 67):
            self._change_wall_color()
    
        elif keycode in (103, 71):
            self._start_generation_animation()

    
        elif keycode in (115, 83):
            self._save_output_file()
        
        elif keycode in (103, 71):
            self._start_generation_animation()

    def _on_close(self, data: Any) -> None:
        """Handle window close button."""
        self._quit()

    def _quit(self) -> None:
        """Quit cleanly."""
        self.mlx.mlx_loop_exit(self.mlx_ptr)

    # ==========================================================
    #  ACTIONS
    # ==========================================================

    def _regenerate(self) -> None:
        """Re-generate a new maze."""
        from mazegen.generator import MazeGenerator

        new_maze = MazeGenerator(
            config=self.maze.config
        )
        new_maze.generate()

        if not new_maze.pattern_placed:
            print("⚠️ 42 pattern omitted (maze too small)")

        self.maze = new_maze
        self._update_path()
        self._start_generation_animation()
        # Reset path animation state
        self._animating = False
        self._path_progress = 0
        self._frame_counter = 0
        self.show_path = False  # Path is hidden by default
        # Reset BFS animation state
        self.bfs_mode = False
        self.bfs_animator = None
        self.bfs_frame_counter = 0
        self.bfs_complete_counter = 0
        self.bfs_final_state = None

    def _change_wall_color(self) -> None:
        """Change wall + related colors randomly, in sync everywhere."""
        self._wall_color = 0xFF000000 | random.randint(0, 0xFFFFFF)
        self.COLORS['wall'] = self._wall_color
        self.COLORS['pattern42'] = self._wall_color

    def _start_bfs_animation(self) -> None:
        """Start the solve animation."""

        algorithm = getattr(self.maze.config, "algorithm", "bfs")

        self.bfs_animator = BFSAnimator(
            self.maze.grid,
            self.entry,
            self.exit_pos,
            algorithm=algorithm,
        )
        self.bfs_animator.solve()
        self.bfs_animator.current_step = 0
        self.bfs_mode = True
        self.bfs_frame_counter = 0
        self.bfs_complete_counter = 0
        self.bfs_final_state = None

        print(f"{algorithm.upper()} animation started!")

    def _bfs_next_step(self) -> None:
        """Advance BFS animation by one step."""
        if self.bfs_mode and self.bfs_animator:
            if self.bfs_animator.is_finished():
                if self.bfs_animator.path:
                    print(f"BFS complete! Path: {len(self.bfs_animator.path)}")
                else:
                    print("BFS complete! No path found")
    
    def _save_output_file(self) -> None:
        """Save maze when S key is pressed."""

        save_maze(
            self.maze,
            self.entry,
            self.exit_pos,
            self._path_directions,
            self.output_file,
        )

        print(f"Maze saved to '{self.output_file}'.")
    
    def _show_solution(self) -> None:
        """Display the complete solution instantly."""
        self._skip_generation_animation()
        self.bfs_mode = False
        self.bfs_animator = None
        self.bfs_final_state = None
        self.bfs_frame_counter = 0
        self.bfs_complete_counter = 0
        self.show_path = True
        self._animating = False
         
    # ==========================================================
    #  RUN & CLEANUP
    # ==========================================================

    def run(self) -> None:
        """Start the MLX loop."""
        self.mlx.mlx_loop(self.mlx_ptr)
        self._cleanup()

    def _cleanup(self) -> None:
        """Release resources (reverse order)."""
        try:
            self.mlx.mlx_destroy_image(self.mlx_ptr, self.img)
            self.mlx.mlx_destroy_window(self.mlx_ptr, self.win)
            self.mlx.mlx_release(self.mlx_ptr)
        except Exception:
            pass


class BFSAnimator:
    """Animate a shortest-path algorithm step by step.

    Despite the name (kept so existing references/keys elsewhere don't
    break), this now drives whichever algorithm is requested (BFS or
    A*) through the shared `solve_animated` entry point in solver.py.
    Both algorithms record steps using the same schema ('visited',
    'frontier', 'current', 'path', 'type'), so this class and the
    `_draw_bfs_step` rendering in MlxDisplay work unchanged for either.
    """

    def __init__(self, grid: list[list[int]], entry: Coord, exit_: Coord,
                 algorithm: str = "bfs"):
        """Initialize animator with maze data.

        Args:
            grid: maze grid with wall bitmasks
            entry: (x, y) starting coordinates
            exit_: (x, y) target coordinates
            algorithm: name of the algorithm to run ("bfs" or "astar"),
                normally taken from config.algorithm.
        """
        self.grid = grid
        self.entry = entry
        self.exit = exit_
        self.algorithm = algorithm
        self.steps: list[dict[str, Any]] = []
        self.current_step: int = 0
        self.path: Optional[list[str]] = None
        self.is_animating: bool = False

    def solve(self) -> None:
        """Run the configured algorithm and store all animation steps."""
        self.path, self.steps = solve_animated(
            self.grid, self.entry, self.exit, self.algorithm)
        self.current_step = 0

    def get_state(self, step_index: int) -> dict[str, Any]:
        """Get the state at a specific step index."""
        if step_index >= len(self.steps):
            return self.steps[-1] if self.steps else {}
        return self.steps[step_index]

    def next_step(self) -> dict[str, Any]:
        """Advance to the next step and return its state."""
        if self.current_step < len(self.steps) - 1:
            self.current_step += 1
        return self.get_state(self.current_step)

    def reset(self) -> None:
        """Reset animation to the beginning."""
        self.current_step = 0

    def is_finished(self) -> bool:
        """Check if animation has reached the end."""
        return self.current_step >= len(self.steps) - 1

    def get_progress(self) -> float:
        """Get animation progress as a float between 0 and 1."""
        if not self.steps:
            return 0.0
        return self.current_step / max(1, len(self.steps) - 1)
