"""Graphical maze display using MiniLibX.

Conforms to the A-Maze-ing subject (Part V - Visual representation).
Adapted for the existing MazeGenerator class.
"""

import random
from typing import Tuple, Set, Optional, Dict, Any, List

from mlx import Mlx
from mazegen.generator import MazeGenerator, ALL_WALLS, EAST, SOUTH
from mazegen.solver import solve


class MlxDisplay:
    """
    MLX maze display for MazeGenerator.

    Implements the interactions required by the subject:
        - Regenerate a maze (R)
        - Show/Hide the solution path (P)
        - Change wall colors (C)
    """

    # Default colors (0xAARRGGBB format)
    COLORS: Dict[str, int] = {
        'wall': 0xFF2C3E50,      # Walls - dark blue
        'floor': 0xFFFFFF00,     # Floor - off-white
        'entry': 0xFF2ECC71,     # Entry - green
        'exit': 0xFFE74C3C,      # Exit - red
        'path': 0xFFF1C40F,      # Path - yellow
        'pattern42': 0xFF9B59B6,    # 42 pattern - purple
    }

    # Wall color (changeable via 'C' key)
    _wall_color: int = COLORS['wall']

    def __init__(self, maze: MazeGenerator, cell_size: int = 30,
                 entry: Tuple[int, int] = (0, 0),
                 exit_pos: Optional[Tuple[int, int]] = None):
        """
        Initialize the MLX window.

        Args:
            maze: Maze generated by MazeGenerator
            cell_size: Cell size in pixels
            entry: Entry coordinates (x, y) - default (0, 0)
            exit_pos: Exit coordinates (x, y) - default (width-1, height-1)
        """
        self.maze = maze
        self.cell_size = cell_size
        self.show_path: bool = True

        # Store entry and exit
        self.entry = entry
        if exit_pos is None:
            self.exit_pos = (maze.width - 1, maze.height - 1)
        else:
            self.exit_pos = exit_pos

        # Solve the path using the solver
        self._path_coords: Set[Tuple[int, int]] = set()
        self._path_directions: List[str] = []
        self._solve_path()

        # Window dimensions (padding + space for info)
        self.width = maze.width * cell_size + 2
        self.height = maze.height * cell_size + 2

        # --- 1. Initialize MLX ---
        self.mlx = Mlx()
        self.mlx_ptr = self.mlx.mlx_init()
        if not self.mlx_ptr:
            raise RuntimeError("mlx_init() failed")

        # --- 2. Create the window ---
        self.win = self.mlx.mlx_new_window(
            self.mlx_ptr,
            self.width,
            self.height,
            "A-Maze-Ing"
        )
        if not self.win:
            self.mlx.mlx_release(self.mlx_ptr)
            raise RuntimeError("mlx_new_window() failed")

        # --- 3. Create the image buffer ---
        self.img = self.mlx.mlx_new_image(
            self.mlx_ptr, self.width, self.height)
        self.data, self.bpp, self.sl, _ = self.mlx.mlx_get_data_addr(self.img)

        # --- 4. Register hooks ---
        self.mlx.mlx_key_hook(self.win, self._on_key, None)
        self.mlx.mlx_hook(self.win, 33, 0, self._on_close, None)
        self.mlx.mlx_loop_hook(self.mlx_ptr, self._render, None)

        print("🎮 MLX Commands:")
        print("  [R] Re-generate a new maze")
        print("  [P] Show/Hide the solution path")
        print("  [C] Change wall colors")
        print("  [Q] Quit")

    def _solve_path(self) -> None:
        """Solve the maze using the solver."""
        path_dirs = solve(self.maze.grid, self.entry, self.exit_pos)

        if path_dirs is None:
            self._path_directions = []
            self._path_coords = set()
            return

        self._path_directions = path_dirs

        # Convert directions to coordinates
        x, y = self.entry
        coords = [(x, y)]
        for d in path_dirs:
            if d == 'N':
                y -= 1
            elif d == 'S':
                y += 1
            elif d == 'E':
                x += 1
            elif d == 'W':
                x -= 1
            coords.append((x, y))

        self._path_coords = set(coords)

    def _update_path(self) -> None:
        """Update path after maze regeneration."""
        self._solve_path()

    # ==========================================================
    #  RENDERING
    # ==========================================================

    def _put_pixel(self, x: int, y: int, color: int) -> None:
        """Write a pixel to the image buffer."""
        if 0 <= x < self.width and 0 <= y < self.height:
            off = y * self.sl + x * (self.bpp // 8)
            self.data[off:off+4] = color.to_bytes(4, 'little')

    def _draw_rect(self, x: int, y: int, w: int, h: int, color: int) -> None:
        """Draw a filled rectangle."""
        for row in range(y, y + h):
            for col in range(x, x + w):
                self._put_pixel(col, row, color)

    def _draw_line(
            self, x1: int, y1: int, x2: int, y2: int, color: int) -> None:
        """Draw a line using Bresenham's algorithm."""
        dx = abs(x2 - x1)
        dy = abs(y2 - y1)
        sx = 1 if x1 < x2 else -1
        sy = 1 if y1 < y2 else -1
        err = dx - dy

        while True:
            self._put_pixel(x1, y1, color)
            if x1 == x2 and y1 == y2:
                break
            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x1 += sx
            if e2 < dx:
                err += dx
                y1 += sy

    def _clear(self) -> None:
        """Clear the buffer to black."""
        size = self.sl * self.height
        self.data[0:size] = b'\x00\x00\x00\xff' * (size // 4)  # ← NOIR

    def _flush(self) -> None:
        """Send the buffer to the window."""
        self.mlx.mlx_put_image_to_window(
            self.mlx_ptr, self.win, self.img, 0, 0)

    def _render(self, data: Any) -> None:
        """Called every frame by mlx_loop_hook."""
        self._clear()
        self._draw_maze()
        self._flush()
        self._draw_info()

    def _draw_thick_line(
            self, x1: int, y1: int, x2: int, y2: int,
            color: int, thickness: int = 4) -> None:
        """Dessine une ligne épaisse."""
        if x1 == x2:  # Ligne verticale
            for i in range(thickness):
                self._draw_line(x1 - i, y1, x2 - i, y2, color)
        elif y1 == y2:  # Ligne horizontale
            for i in range(thickness):
                self._draw_line(x1, y1 - i, x2, y2 - i, color)
        else:
            # Ligne diagonale - on utilise plusieurs lignes décalées
            for i in range(thickness):
                self._draw_line(x1 - i, y1 - i, x2 - i, y2 - i, color)

    def _draw_maze(self) -> None:
        """Draw the maze using self.maze.grid directly."""
        grid = self.maze.grid

        # Use path coords only if show_path is True
        path_coords = self._path_coords if self.show_path else set()

        for y in range(self.maze.height):
            for x in range(self.maze.width):
                px = x * self.cell_size + 1
                py = y * self.cell_size + 1

                walls = grid[y][x]

                entry_x, entry_y = self.entry
                exit_x, exit_y = self.exit_pos
                if (x, y) == (entry_x, entry_y):
                    color = self.COLORS['entry']
                    self._draw_rect(
                        px, py, self.cell_size, self.cell_size, color)
                elif (x, y) == (exit_x, exit_y):
                    color = self.COLORS['exit']
                    self._draw_rect(
                        px, py, self.cell_size, self.cell_size, color)
                elif (x, y) in path_coords:
                    color = self.COLORS['path']
                    self._draw_rect(
                        px, py, self.cell_size, self.cell_size, color)
                elif walls == ALL_WALLS:
                    color = self.COLORS['pattern42']
                    self._draw_rect(
                        px, py, self.cell_size, self.cell_size, color)

                wall_color = self._wall_color
                if walls & EAST:
                    self._draw_thick_line(px + self.cell_size, py,
                                          px + self.cell_size,
                                          py + self.cell_size, wall_color)
                if walls & SOUTH:
                    self._draw_thick_line(px, py + self.cell_size,
                                          px + self.cell_size,
                                          py + self.cell_size, wall_color)

        # Outer borders
        wall_color = self._wall_color
        self._draw_rect(0, 0, self.width, 1, wall_color)
        self._draw_rect(0, self.height - 1, self.width, 1, wall_color)
        self._draw_rect(0, 0, 1, self.height, wall_color)
        self._draw_rect(self.width - 1, 0, 1, self.height, wall_color)

    def _draw_info(self) -> None:
        """Display information at the bottom of the window."""
        y = self.maze.height * self.cell_size + 5
        steps = len(self._path_directions)

        text = (f"Size: {self.maze.width}x{self.maze.height} | "
                f"Path: {'ON' if self.show_path else 'OFF'} | "
                f"Steps: {steps} | "
                f"42: {'✅' if self.maze.pattern_placed else '⚠️'}")

        self.mlx.mlx_string_put(
            self.mlx_ptr, self.win, 10, y + 25, 0xFFFFFFFF, text)

    # ==========================================================
    #  EVENT HANDLERS
    # ==========================================================

    def _on_key(self, keycode: int, data: Any) -> None:
        """Handle keyboard events."""
        # Escape (65307) or Q (113)
        if keycode == 65307 or keycode == 113:
            self._quit()
        # R (114 or 82)
        elif keycode == 114 or keycode == 82:
            self._regenerate()
        # P (112 or 80)
        elif keycode == 112 or keycode == 80:
            self.show_path = not self.show_path
        # C (99 or 67)
        elif keycode == 99 or keycode == 67:
            self._change_wall_color()

    def _on_close(self, data: Any) -> None:
        """Handle window close button."""
        self._quit()

    def _quit(self) -> None:
        """Quit cleanly."""
        self.mlx.mlx_loop_exit(self.mlx_ptr)

    # ==========================================================
    #  ACTIONS
    # ==========================================================

    def _regenerate(self) -> None:
        """Re-generate a new maze."""
        from mazegen.generator import MazeGenerator

        new_maze = MazeGenerator(
            config=self.maze.config
        )
        new_maze.generate()

        if not new_maze.pattern_placed:
            print("⚠️ 42 pattern omitted (maze too small)")

        self.maze = new_maze
        self._update_path()

    def _change_wall_color(self) -> None:
        """Change wall colors randomly."""
        self._wall_color = 0xFF000000 | random.randint(0, 0xFFFFFF)

    # ==========================================================
    #  RUN & CLEANUP
    # ==========================================================

    def run(self) -> None:
        """Start the MLX loop."""
        self.mlx.mlx_loop(self.mlx_ptr)
        self._cleanup()

    def _cleanup(self) -> None:
        """Release resources (reverse order)."""
        try:
            self.mlx.mlx_destroy_image(self.mlx_ptr, self.img)
            self.mlx.mlx_destroy_window(self.mlx_ptr, self.win)
            self.mlx.mlx_release(self.mlx_ptr)
        except Exception:
            pass
