"""Graphical maze display using MiniLibX.

Conforms to the A-Maze-ing subject (Part V - Visual representation).
Adapted for the existing MazeGenerator class.
"""

import random
from typing import Tuple, Set, Optional, Dict, Any, List

from mlx import Mlx
from mazegen.generator import MazeGenerator, ALL_WALLS, EAST, SOUTH
from mazegen.solver import solve


class MlxDisplay:
    """
    MLX maze display for MazeGenerator.

    Implements the interactions required by the subject:
        - Regenerate a maze (R)
        - Show/Hide the solution path (P)
        - Change wall colors (C)
    """

    # Default colors (0xAARRGGBB format)
    COLORS: Dict[str, int] = {
        'wall': 0xFFFFFFFF,      # Walls - WHITE
        'floor': 0xFF000000,     # Floor - BLACK
        'entry': 0xFF2ECC71,     # Entry - GREEN (keep visible)
        'exit': 0xFFE74C3C,      # Exit - RED (keep visible)
        'path': 0xFF888888,      # Path - MEDIUM GRAY
        'pattern42': 0xFFFFFFFF,  # 42 pattern - WHITE
    }
    # Wall color (changeable via 'C' key)
    _wall_color: int = COLORS['wall']

    def __init__(self, maze: MazeGenerator, cell_size: int = 30,
                 entry: Tuple[int, int] = (0, 0),
                 exit_pos: Optional[Tuple[int, int]] = None):
        """
        Initialize the MLX window.

        Args:
            maze: Maze generated by MazeGenerator
            cell_size: Cell size in pixels
            entry: Entry coordinates (x, y) - default (0, 0)
            exit_pos: Exit coordinates (x, y) - default (width-1, height-1)
        """
        self.maze = maze
        self.cell_size = cell_size
        self.show_path: bool = False  # Path hidden by default

        # Store entry and exit
        self.entry = entry
        if exit_pos is None:
            self.exit_pos = (maze.width - 1, maze.height - 1)
        else:
            self.exit_pos = exit_pos

        # --- Animation attributes ---
        self._path_cells: List[Tuple[int, int]] = []
        self._path_progress: int = 0
        self._animating: bool = False
        self._frame_counter: int = 0
        self._animation_speed: int = 1
        self._path_dir_map: Dict[Tuple[int, int], str] = {}

        # Solve the path using the solver
        self._path_coords: Set[Tuple[int, int]] = set()
        self._path_directions: List[str] = []
        self._solve_path()

        # Window dimensions (padding + space for info)
        self.width = maze.width * cell_size + 2
        self.height = maze.height * cell_size + 2

        # --- 1. Initialize MLX ---
        self.mlx = Mlx()
        self.mlx_ptr = self.mlx.mlx_init()
        if not self.mlx_ptr:
            raise RuntimeError("mlx_init() failed")

        # --- 2. Create the window ---
        self.win = self.mlx.mlx_new_window(
            self.mlx_ptr,
            self.width,
            self.height,
            "A-Maze-Ing"
        )
        if not self.win:
            self.mlx.mlx_release(self.mlx_ptr)
            raise RuntimeError("mlx_new_window() failed")

        # --- 3. Create the image buffer ---
        self.img = self.mlx.mlx_new_image(
            self.mlx_ptr, self.width, self.height)
        self.data, self.bpp, self.sl, _ = self.mlx.mlx_get_data_addr(self.img)

        # --- 4. Register hooks ---
        self.mlx.mlx_key_hook(self.win, self._on_key, None)
        self.mlx.mlx_hook(self.win, 33, 0, self._on_close, None)
        self.mlx.mlx_loop_hook(self.mlx_ptr, self._render, None)

        print("🎮 MLX Commands:")
        print("  [R] Re-generate a new maze")
        print("  [P] Show/Hide the solution path (step by step)")
        print("  [C] Change wall colors")
        print("  [Q] Quit")

    def _solve_path(self) -> None:
        """Solve the maze and store ordered cells with directions."""
        path_dirs = solve(self.maze.grid, self.entry, self.exit_pos)

        if path_dirs is None:
            self._path_directions = []
            self._path_coords = set()
            self._path_cells = []
            self._path_dir_map = {}
            return

        self._path_directions = path_dirs

        # Convert directions to coordinates (ordered list)
        x, y = self.entry
        coords = [(x, y)]
        dir_map = {}
        for d in path_dirs:
            dir_map[(x, y)] = d  # Store direction for current cell
            if d == 'N':
                y -= 1
            elif d == 'S':
                y += 1
            elif d == 'E':
                x += 1
            elif d == 'W':
                x -= 1
            coords.append((x, y))

        self._path_cells = coords
        self._path_coords = set(coords)
        self._path_dir_map = dir_map

    def _update_path(self) -> None:
        """Update path after maze regeneration."""
        self._solve_path()

    # ==========================================================
    #  RENDERING
    # ==========================================================

    def _put_pixel(self, x: int, y: int, color: int) -> None:
        """Write a pixel to the image buffer."""
        if 0 <= x < self.width and 0 <= y < self.height:
            off = y * self.sl + x * (self.bpp // 8)
            self.data[off:off+4] = color.to_bytes(4, 'little')

    def _draw_rect(self, x: int, y: int, w: int, h: int, color: int) -> None:
        """Draw a filled rectangle."""
        for row in range(y, y + h):
            for col in range(x, x + w):
                self._put_pixel(col, row, color)

    def _draw_line(
            self, x1: int, y1: int, x2: int, y2: int, color: int) -> None:
        """Draw a line using Bresenham's algorithm."""
        dx = abs(x2 - x1)
        dy = abs(y2 - y1)
        sx = 1 if x1 < x2 else -1
        sy = 1 if y1 < y2 else -1
        err = dx - dy

        while True:
            self._put_pixel(x1, y1, color)
            if x1 == x2 and y1 == y2:
                break
            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x1 += sx
            if e2 < dx:
                err += dx
                y1 += sy

    def _draw_thick_line(
            self, x1: int, y1: int, x2: int, y2: int,
            color: int, thickness: int = 4) -> None:
        """Draw a thick line."""
        if x1 == x2:  # Vertical line
            for i in range(thickness):
                self._draw_line(x1 - i, y1, x2 - i, y2, color)
        elif y1 == y2:  # Horizontal line
            for i in range(thickness):
                self._draw_line(x1, y1 - i, x2, y2 - i, color)
        else:  # Diagonal line - offset multiple lines
            for i in range(thickness):
                self._draw_line(x1 - i, y1 - i, x2 - i, y2 - i, color)

    def _draw_arrow(self, cx: int, cy: int, direction: str, color: int,
                    size: int = 10, thickness: int = 2) -> None:
        """Draw an arrow centered at (cx, cy) pointing in direction."""
        half = size // 2

        if direction == 'N':
            x1, y1 = cx, cy + half
            x2, y2 = cx, cy - half
            x3, y3 = cx - half//2, cy - half//2
            x4, y4 = cx + half//2, cy - half//2
        elif direction == 'S':
            x1, y1 = cx, cy - half
            x2, y2 = cx, cy + half
            x3, y3 = cx - half//2, cy + half//2
            x4, y4 = cx + half//2, cy + half//2
        elif direction == 'E':
            x1, y1 = cx - half, cy
            x2, y2 = cx + half, cy
            x3, y3 = cx + half//2, cy - half//2
            x4, y4 = cx + half//2, cy + half//2
        elif direction == 'W':
            x1, y1 = cx + half, cy
            x2, y2 = cx - half, cy
            x3, y3 = cx - half//2, cy - half//2
            x4, y4 = cx - half//2, cy + half//2
        else:
            return

        # Body of the arrow
        self._draw_thick_line(x1, y1, x2, y2, color, thickness)
        # Arrowhead
        self._draw_line(x2, y2, x3, y3, color)
        self._draw_line(x2, y2, x4, y4, color)

    def _clear(self) -> None:
        """Clear the buffer to black."""
        size = self.sl * self.height
        self.data[0:size] = b'\x00\x00\x00\xff' * (size // 4)

    def _flush(self) -> None:
        """Send the buffer to the window."""
        self.mlx.mlx_put_image_to_window(
            self.mlx_ptr, self.win, self.img, 0, 0)

    def _render(self, data: Any) -> None:
        """Called every frame by mlx_loop_hook."""
        # Progressive animation
        if self._animating:
            self._frame_counter += 1
            if self._frame_counter >= self._animation_speed:
                self._frame_counter = 0
                if self._path_progress < len(self._path_cells):
                    self._path_progress += 1
                else:
                    self._animating = False  # Animation complete

        self._clear()
        self._draw_maze()
        self._flush()
        self._draw_info()

    def _draw_maze(self) -> None:
        """Draw the maze with progressive path display."""
        grid = self.maze.grid

        # Visible path cells (progressive or full)
        visible_path = set()
        if self.show_path:
            if self._animating:
                limit = self._path_progress
            else:
                limit = len(self._path_cells)
            visible_path = set(self._path_cells[:limit])

        for y in range(self.maze.height):
            for x in range(self.maze.width):
                px = x * self.cell_size + 1
                py = y * self.cell_size + 1
                walls = grid[y][x]

                # --- Determine background color ---
                if (x, y) == self.entry:
                    color = self.COLORS['entry']
                elif (x, y) == self.exit_pos:
                    color = self.COLORS['exit']
                elif (x, y) in visible_path:
                    color = self.COLORS['path']  # Highlight path cells
                elif walls == ALL_WALLS:
                    color = self.COLORS['pattern42']
                else:
                    color = self.COLORS.get('floor', 0xFFFFFFFF)

                self._draw_rect(px, py, self.cell_size, self.cell_size, color)

                # --- Draw arrow if cell is in path (except entry/exit) ---
                pos = (x, y)
                if (
                     pos in visible_path and
                     pos not in (self.entry, self.exit_pos)):
                    direction = self._path_dir_map.get((x, y))
                    if direction:
                        cx = px + self.cell_size // 2
                        cy = py + self.cell_size // 2
                        arrow_size = self.cell_size // 3  # Smaller arrow
                        self._draw_arrow(
                            cx, cy, direction,
                            self.COLORS['path'],
                            size=arrow_size, thickness=2)

                # --- Walls ---
                wall_color = self._wall_color
                if walls & EAST:
                    self._draw_thick_line(
                        px + self.cell_size, py,
                        px + self.cell_size, py + self.cell_size,
                        wall_color, thickness=2)
                if walls & SOUTH:
                    self._draw_thick_line(px, py + self.cell_size,
                                          px + self.cell_size,
                                          py + self.cell_size,
                                          wall_color, thickness=2)

        # Outer borders
        wall_color = self._wall_color
        self._draw_thick_line(0, 0, self.width, 0, wall_color, thickness=2)
        self._draw_thick_line(0, self.height - 1, self.width, self.height - 1,
                              wall_color, thickness=2)
        self._draw_thick_line(0, 0, 0, self.height, wall_color, thickness=2)
        self._draw_thick_line(self.width - 1, 0, self.width - 1, self.height,
                              wall_color, thickness=2)

    def _draw_info(self) -> None:
        """Display information at the bottom of the window."""
        y = self.maze.height * self.cell_size + 5
        steps = len(self._path_directions)

        text = (f"Size: {self.maze.width}x{self.maze.height} | "
                f"Path: {'ON' if self.show_path else 'OFF'} | "
                f"Steps: {steps} | "
                f"42: {'✅' if self.maze.pattern_placed else '⚠️'}")

        self.mlx.mlx_string_put(
            self.mlx_ptr, self.win, 10, y + 25, 0xFFFFFFFF, text)

    # ==========================================================
    #  EVENT HANDLERS
    # ==========================================================

    def _on_key(self, keycode: int, data: Any) -> None:
        """Handle keyboard events."""
        # Escape (65307) or Q (113)
        if keycode == 65307 or keycode == 113:
            self._quit()
        # R (114 or 82) - Regenerate
        elif keycode == 114 or keycode == 82:
            self._regenerate()
        # P (112 or 80) - Toggle path with step-by-step animation
        elif keycode == 112 or keycode == 80:
            if self.show_path:
                # If path is already shown, hide it
                self.show_path = False
                self._animating = False
            else:
                # Start progressive animation from beginning
                self._animating = True
                self._path_progress = 0
                self._frame_counter = 0
                self.show_path = True
        # C (99 or 67) - Change wall color
        elif keycode == 99 or keycode == 67:
            self._change_wall_color()

    def _on_close(self, data: Any) -> None:
        """Handle window close button."""
        self._quit()

    def _quit(self) -> None:
        """Quit cleanly."""
        self.mlx.mlx_loop_exit(self.mlx_ptr)

    # ==========================================================
    #  ACTIONS
    # ==========================================================

    def _regenerate(self) -> None:
        """Re-generate a new maze."""
        from mazegen.generator import MazeGenerator

        new_maze = MazeGenerator(
            config=self.maze.config
        )
        new_maze.generate()

        if not new_maze.pattern_placed:
            print("⚠️ 42 pattern omitted (maze too small)")

        self.maze = new_maze
        self._update_path()
        # Reset animation state
        self._animating = False
        self._path_progress = 0
        self._frame_counter = 0
        self.show_path = False  # Path is hidden by default

    def _change_wall_color(self) -> None:
        """Change wall colors randomly."""
        self._wall_color = 0xFF000000 | random.randint(0, 0xFFFFFF)
        self.COLORS['pattern42'] = self._wall_color

    # ==========================================================
    #  RUN & CLEANUP
    # ==========================================================

    def run(self) -> None:
        """Start the MLX loop."""
        self.mlx.mlx_loop(self.mlx_ptr)
        self._cleanup()

    def _cleanup(self) -> None:
        """Release resources (reverse order)."""
        try:
            self.mlx.mlx_destroy_image(self.mlx_ptr, self.img)
            self.mlx.mlx_destroy_window(self.mlx_ptr, self.win)
            self.mlx.mlx_release(self.mlx_ptr)
        except Exception:
            pass
